# Generated by Django 6.0.1 on 2026-03-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_taskcomment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcomment',
            name='desLikes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
