# Generated by Django 6.0.1 on 2026-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_taskcomment_deslikes_taskcomment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='content',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
