# Generated by Django 6.0.1 on 2026-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_alter_taskcomment_content_alter_taskcomment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='desLikes',
            field=models.IntegerField(default=0),
        ),
    ]
