# Generated by Django 6.0.1 on 2026-03-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_workspaceinvite_expires_at_and_more'),
        ('workspaces', '0002_workspacemember'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspaceinvite',
            unique_together={('workspace', 'email')},
        ),
    ]
